#cloud-config
hostname: gt-mail
users:
  - name: ubuntu
    gecos: Admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - "{{ SSH_PUB_KEY_PLACEHOLDER }}"
package_update: true
packages:
  - postfix
  - dovecot-core
  - dovecot-imapd
runcmd:
  - [ sh, -lc, 'echo "127.0.0.1 gt-mail.germetech.local gt-mail" >> /etc/hosts' ]
  - [ sh, -lc, 'systemctl enable postfix' ]
  - [ sh, -lc, 'systemctl start postfix' ]
